config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists, only: %i[show new create index] do
    resources :bookmarks, only: %i[new create]
  end
end
# nester la route bookmarks pour récupérer l'id de la liste = http/lists/1/bookmarks

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), alert: 'Bookmark added successfully.'
    else
      render :new, status: :unprocessable_entity, alert: 'Bookmark could not be added.'
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def index
    @lists = List.all
    @list = List.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List created successfully.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    @movies = Movie.find(params[:id])
  end

  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Hello, create your new list</h1>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Create List" %>
<% end %>

<h2>Here are your lists  </h2>
<ul>
  <% @lists.each do |list| %>
    <li>
      <%= list.name %>
      <%= link_to "View List", list_path(list) %>
    </li>
  <% end %>
</ul>

app/views/lists/list.html.erb
<ul>
  <% @lists.each do |list| %>
    <li>
      <%= list.name %>
      <%= list.submit %>
    </li>
  <% end %>
</ul>

app/views/lists/show.html.erb
<h1><%= @list.name %> List</h1>

<h2>Movies:</h2>
<ul>
  <% @movies.each do |movie| %>
    <li><%= movie.title %></li>
    <ul>
      <% movie.bookmarks.each do |bookmark| %>
        <li><%= bookmark.comment %></li>
      <% end %>
    </ul>
  <% end %>
</ul>

<%= link_to 'Back to Lists', lists_path %>
<%= link_to 'Create Bookmark', new_list_bookmark_path(@list)%>

app/views/movies/index.html.erb
<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= movie.title %>
      <%= movie.overwiew %>
      <%= movie.poster_url %>
      <%= movie.raing %>
      <%= movie.submit %>
    </li>
  <% end %>
</ul>

app/views/movies/show.html.erb
<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= movie.title %>
      <%= movie.overwiew %>
      <%= movie.poster_url %>
      <%= movie.rating %>
      <%= movie.submit %>
    </li>
  <% end %>
</ul>